### PR TITLE
Add new tempalte functions for trimming unneeded spaces in strings

### PR DESCRIPTION
**Pull request by icecream78**
Hi. In some cases, meta fields contain unneeded new line characters. I add three new template functions:
- trim for trimming leading and trailing spaces
- trimLeft
- trimRight
Please, add this functions to main branch for start using it in telegram plugin=)
Thanks and have a good day!

### CODE REVIEW

**Comment by icecream78** [comment]
cc @tboerger @bradrydzewski

**Comment by tboerger** [comment]
Sprig already provides these helpers: http://masterminds.github.io/sprig/strings.html

**Comment by icecream78** [comment]
There is no methods for cutting new line characters.

**Comment by tboerger** [comment]
There is already `trimSuffix` and `trimPrefix` beside other trim functions.

**Comment by icecream78** [comment]
Ohh, I apologize. I made changes so late and write message not according to logic, what I made. I wrote logic for cutting new line characters **(\n and \r\n)**, but commit message and PR description is wrong. Should i close this PR and open another with proper description?

**Comment by tboerger** [comment]
I'm not sure if these helpers are really needed as they are just wrappers to functionality that is already available today.

**Comment by icecream78** [comment]
OK, decide merge or not this changes. In my opinion It is more easier call helper trim, then call built-in function and specify new line characters to trim.

**Comment by icecream78** [comment]
@tboerger closing or not issue?

**Pull request closed without merging**
