### PR TITLE
Adding custom helper for regex

### PR DESCRIPTION
**Pull request by chrisevett**
The use case here is so I can do a regex replace in json payloads for the drone webhook plugin. Let me know if you have any questions.

### CODE REVIEW

**Review by tboerger — APPROVED** [review]

**Comment by chrisevett** [comment]
Thanks for the approve. Anything I need to do before this gets merged?

**Comment by tboerger** [comment]
I would like to get another opinion of the other maintainers.

**Comment by chrisevett** [comment]
Noticed an issue during further testing, the help wasnt actually registered before.

**Comment by chrisevett** [comment]
Any update on this? I'm maintaining a fork right now and I would really rather not have to do that 😃

**Comment by tboerger** [comment]
Now I have merged it without another opinion, looks like no other is interested :)

**Comment by chrisevett** [comment]
Thanks!

**Pull request merged**
